spring:
  datasource:
    url: jdbc:mysql://localhost:3307/honeydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or validate / create / none, based on your need
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: 8080

# Optional CORS if React is on localhost:3000
cors:
  allowed-origins: http://localhost:3000

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY} 
  success:
    url: http://localhost:3000/success
  cancel:
    url: http://localhost:3000/cancel    



