spring:
  datasource:
    url: jdbc:postgresql://dpg-d2aj9teuk2gs73a55tfg-a.oregon-postgres.render.com:5432/honeydb
    username: honeydb_user
    password: MqJUyNmJNYKHAgFSnGmjeap5g6g83Up9
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update  # or validate / create / none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8080

cors:
  allowed-origins: http://localhost:3000

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  success:
    url: http://localhost:3000/success
  cancel:
    url: http://localhost:3000/cancel
